import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";
import { useRef, useState } from "react";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";

import React from "react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

import IMG1 from "../images/Wellness Forever-1.png";
import IMG2 from "../images/Wellness Forever-2.png";
import IMG3 from "../images/Wellness Forever-3.png";
import IMG4 from "../images/Wellness Forever-4.png";

// import required modules
import { Pagination, Navigation } from "swiper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wellness Forever</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-2 py-20">
        <Swiper
          pagination={{
            type: "fraction",
          }}
          navigation={true}
          modules={[Pagination, Navigation]}
          className="mySwiper"
        >
          <div className="swiper-wrapper mx-4 ">
            <SwiperSlide>
              <Image src={IMG1} alt="Picture of the author" />
            </SwiperSlide>
            <SwiperSlide>
              <Image src={IMG2} alt="Picture of the author" />
            </SwiperSlide>
            <SwiperSlide>
              <Image src={IMG3} alt="Picture of the author" />
            </SwiperSlide>
            <SwiperSlide>
              <Image src={IMG4} alt="Picture of the author" />
            </SwiperSlide>
          </div>
        </Swiper>
      </div>
    </>
  );
}
